spring:
  profiles:
    active: local
    include: db
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: true
