spring:
  config:
    activate:
      on-profile: local

jwt:
  secretKey:

  access:
    expiration: 360000  # 1시간
    header: Authorization

  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh
