spring:
  profiles:
    active: local
    include:
      - db
      - jwt
  oauth:
    kakao:
      secret: YmkpW6daM1UdRVPcLUx979MAaFNiIVt5
      client-id: e0df3d8e0617f4bba3f0c3c909eef6ea
      url:
        auth: https://kauth.kakao.com
        api: https://kapi.kakao.com

#server:
#  port: 80

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: true

logging:
  level:
    org:
      springframework:
        security: DEBUG