spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3307/sulsul
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

---
spring:
  config:
    activate:
      on-profile: dev, prod

  datasource:
    url: ${SULSUL_DB_URL}
    username: ${SULSUL_DB_USERNAME}
    password: ${SULSUL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
