spring:
  profiles:
    active: local
    include: db
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health
