spring:
  profiles:
    active: dev
    include:
      - db
      - jwt
      - oauth

#server:
#  port: 80

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org:
      springframework:
        security: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
