name: sulsul server CI/CD

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  S3_BUCKET_NAME: sulsul-s3-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses:  actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    - name: Make zip file
      run: zip -r ./sulsul.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./sulsul.zip s3://$S3_BUCKET_NAME/
